#Perfis
spring.profiles.active=@spring.profiles.active@

#Configurações de Ambiente
spring.config.import=classpath:env.properties

spring.application.name=barbearia
server.port=9000
spring.output.ansi.enabled=always

#JPA/Hibernate/ORM:
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Inicialização no banco de dados com scripts SQL:
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.encoding=UTF-8
spring.sql.init.platform=mysql
